notes: PTR records will automatically be created
unifiConfig:
  config:
    username: homeauto
    password: '******'
    hostname: https://10.0.1.1
  enabled: true
  ignoreMacs:
  - 60:22:32:9f:0f:fd
listeners:
- port: 53
  proto: udp
- port: 53
  proto: tcp
nameservers:
- ip: 127.0.0.1
  port: 53
  proto: tcp
